version: "3"

services:
  job-portal:
    container_name: job-portal
    image: job-portal-api
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
      - .postgres.job.env
      - .auth.env
      - .redis.env
    depends_on:
      - postgres
      - redis
    restart: always
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .postgres.env
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
